apiVersion: v1
kind: Service
metadata:
  labels:
    app: webshop
    type: canary
    version: v1
  name: webshop
  namespace: default
  resourceVersion: "155765"
  uid: 9af6cf8c-6b8a-453f-9bed-e1900e30e5d7
spec:
  clusterIP: 10.106.225.111
  clusterIPs:
  - 10.106.225.111
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http-webshop
  selector:
    app: webshop
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
